# For more details, see https://docs.github.com/en/actions
name: Build devenv

# Controls when the workflow will run
on: workflow_dispatch

defaults:
  run:
    shell: bash

# For more details, see https://github.com/docker/build-push-action
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: zhuoqiw/devenv:22.04
          cache-from: type=registry,ref=zhuoqiw/devenv:22.04
          cache-to: type=inline
