# For more details, see https://docs.github.com/en/actions
name: docker build

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      ubuntu_code:
        description: 'Ubuntu version'
        required: true
        default: '22.04'
        type: choice
        options:
        - '20.04'
        - '22.04'
      platforms:
        description: 'Host platforms'
        required: true
        default: 'linux/amd64,linux/arm64'
        type: choice
        options:
        - 'linux/amd64,linux/arm64'
        - 'linux/amd64'
        - 'linux/arm64'

# For more details, see https://github.com/docker/build-push-action
jobs:
  build:
    name: ${{ github.ref_name }}
    uses: zhuoqiw/docker-build-push/.github/workflows/main.yml@master
    with:
      ubuntu_code: ${{ inputs.ubuntu_code }}
      platforms: ${{ inputs.platforms }}
    secrets: inherit
